"""Added serverConfig

Revision ID: c4ddeeb04651
Revises: dfb4ea6c53e9
Create Date: 2020-11-08 16:51:07.746632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4ddeeb04651'
down_revision = 'dfb4ea6c53e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cameraOrientation', sa.Integer(), nullable=True),
    sa.Column('temperatureDelta', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('server_config')
    # ### end Alembic commands ###
